### ISSUE TITLE
freeze when finished watching

### ISSUE THREAD

**Issue by alakreasi** [darwin-morocho/flutter-meedu-player#32]
I have a problem, when I finish watching more than 20 minutes, the app freezes.

**Comment by darwin-morocho** [comment]
> I have a problem, when I finish watching more than 20 minutes, the app freezes.

Hi @alakreasi could you provide your code. Also remember this plugin use the official [video_player](https://pub.dev/packages/video_player) plugin maybe is a problem of this.

**Comment by alakreasi** [comment]
when my application was published, many users experienced freezes. 
I tried it on Realme 5i. 
bug occurs when exiting fullscreen.

i use StreamSubscription to get the position and save it to sqlite.

this is my `pubspec.yaml`
```yaml
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  rxdart: ^0.24.1
  video_player: ^1.0.1
  flutter_local_notifications: ^3.0.2
  shared_preferences: ^0.5.12+4
  http: ^0.12.2
  sqflite: ^1.3.2+1
  path_provider: ^1.6.24
  fluttertoast: ^7.1.5
  url_launcher: ^5.7.10
  share: ^0.6.5+4
  cached_network_image: ^2.4.1
  meedu_player: ^0.4.0
  flutter_downloader: ^1.5.2
  permission_handler: ^5.0.1+1
  device_info: ^1.0.0
  package_info: ^0.4.3+2
  connectivity: ^2.0.2
  flutter_html: ^1.1.1
  google_sign_in: ^4.5.6
  flutter_facebook_login: ^3.0.0
  firebase_messaging: ^7.0.3
  adsunity: ^1.0.3
  applovin: ^1.0.3
  uni_links: ^0.4.0
  imei_plugin: ^1.2.0
  wakelock: ^0.2.1+1
```
